# Generated by Django 4.2.26 on 2025-11-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_options_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('3', 'Low'), ('2', 'medium'), ('1', 'High')], default='L', max_length=10),
        ),
    ]
