# Generated by Django 4.2.26 on 2025-11-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_due_date_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'medium'), ('H', 'High')], default='L', max_length=10),
        ),
    ]
