# Generated by Django 4.2.26 on 2025-11-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
